export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";

export const PURCHASE_INGREDIENT_FAIL = "PURCHASE_INGREDIENT_FAIL";
export const PURCHASE_INGREDIENT_SUCCESS = "PURCHASE_INGREDIENT_SUCCES";
export const PURCHASE_INGREDIENT_START = "PURCHASE_INGREDIENT_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
