export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";

export const PURCHASE_INGREDIENT = "PURCHASE_INGREDIENT";
export const PURCHASE_INGREDIENT_FAIL = "PURCHASE_INGREDIENT_FAIL";
export const PURCHASE_INGREDIENT_SUCCESS = "PURCHASE_INGREDIENT_SUCCES";
export const PURCHASE_INGREDIENT_START = "PURCHASE_INGREDIENT_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";

export const AUTH_USER = "AUTH_USER";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
